### ISSUE TITLE
Not working in my Swift project

### ISSUE THREAD

**Issue by Framnk** [fcanas/ios-color-picker#14]
Can't figure it out, I copy the Swift example code pretty much verbatim but when I try to show the color picker in a button action I just get a grey background, no color picker.  Any ideas?

**Comment by fcanas** [comment]
Without seeing your project it's here to know what it could be. Did you copy the image and nib resources? Did you load the view controller from the nib?

**Comment by sabiland** [comment]
I had the same issue as Framnk. Resources (colormap.png & xib) must be copied to your project.

**Comment by literalpie** [comment]
I also had this problem and sabiland's comment helped me. Thanks! Maybe this should be in the documentation
