### ISSUE TITLE
Error using in project with deployment target iOS 9.3

### ISSUE THREAD

**Issue by zapjonny** [fcanas/ios-color-picker#17]
At build time, this is the warning:

> /Pods/iOS-Color-Picker/FCColorPickerViewController.xib: warning: Unsupported Configuration: This file is set to build for a version older than the deployment target. Functionality may be limited.

And at runtime it excepts out with

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/94CE8315-3EF7-4415-879D-95D2B182EE46/test.app> (loaded)' with name 'FCColorPickerViewController''

**Comment by fcanas** [comment]
It may just be a matter of opening the xib and updating its version. Would you be interested in trying that and contributing back the change?

**Comment by paulnicholson** [comment]
@zapjonny I believe the runtime exception was fixed in master by #10. I will submit a PR for the build warning. @fcanas Could you push an update to cocoa pods after merging the fix for the build warning?

**Comment by zapjonny** [comment]
OK thanks but not using this right now.
